## Numpy

## library for scientific calculations. Provide supports for arrays and matrices.

In [1]:
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 3.5 MB/s eta 0:00:00a 0:00:01


In [7]:
import numpy as np

arr1 = np.array([1,2,3])
arr1
print(arr1.shape)
print(type(arr1))

(3,)
<class 'numpy.ndarray'>


In [10]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [11]:
arr2=np.array([[1,2,3,4,5]])
arr2

array([[1, 2, 3, 4, 5]])

In [15]:
arr2=np.array([[1,2,3,4,5],[6,5,4,7,8]])
arr2
arr2.shape

(2, 5)

In [17]:
# 2d array
arr2

array([[1, 2, 3, 4, 5],
       [6, 5, 4, 7, 8]])

In [18]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [20]:
np.arange(0,10,-1)

array([], dtype=int64)

In [22]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
## Idendity matrix

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
arr1.ndim

1

In [25]:
arr2.ndim

2

In [26]:
arr1.itemsize

8

In [27]:
## Numpy Vectorized operation

## Element wise

arr1 = np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

print("Addition", arr1+arr2)
print("Subtraction", arr1-arr2)
print("Multiplication", arr1*arr2)

Addition [11 22 33 44 55]
Subtraction [ -9 -18 -27 -36 -45]
Multiplication [ 10  40  90 160 250]


In [28]:
##Universal Functions

arr = np.array([2,3,4,5,6])

print(np.sqrt(arr))

print(np.exp(arr))

print(np.sin(arr))

print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [31]:
## Array Slicing and Indexing

arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)


Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:
print(arr[0])
print(arr[0:2, 2:])
print(arr[1:, 1:3])

[1 2 3 4]
[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]


In [35]:
print(arr[0][0])

1


In [38]:
arr[1:, 2:]

array([[ 7,  8],
       [11, 12]])

In [43]:
# Modify array elements

arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [44]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [45]:
## Statistical Concepts --- NORMALIZATION
## To have a mean of 0 and Standard Deviation of 1

data = np.array([1,2,3,4,5])

# Calculate the mean and Deviation
mean = np.mean(data)
std_dev=np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print(normalized_data)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [46]:
np.var(data)
np.median(data)

np.float64(3.0)

In [47]:
## Logical Operations
data = np.array([1,2,3,4,5,6,7])

data[data>5]

array([6, 7])

In [48]:
data>5

array([False, False, False, False, False,  True,  True])